/**
 * Real-Time Agent Coaching Component
 * 
 * Provides live AI-powered coaching prompts to agents during active calls.
 * Inspired by Taalk.ai's "Magic Coaching" feature.
 * 
 * Features:
 * - Real-time call transcription monitoring
 * - AI-generated coaching suggestions
 * - Objection handling prompts
 * - Compliance reminders
 * - Next-best-action recommendations
 * - Script guidance
 */

import { useState, useEffect } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Lightbulb, AlertTriangle, CheckCircle2, TrendingUp, MessageSquare, Shield } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

export interface CoachingPrompt {
  id: string;
  type: 'suggestion' | 'objection' | 'compliance' | 'next-action' | 'script' | 'warning';
  priority: 'high' | 'medium' | 'low';
  title: string;
  message: string;
  trigger: string;
  timestamp: Date;
  actionable: boolean;
}

interface RealTimeCoachingProps {
  callId: string;
  agentId: string;
  leadId?: string;
  campaignId?: string;
  promptIntervalSeconds?: number; // Configurable interval for prompt generation
  onPromptAction?: (promptId: string, action: string) => void;
}

export const RealTimeCoaching = ({
  callId,
  agentId,
  leadId,
  campaignId,
  promptIntervalSeconds = 15, // Default 15 seconds, but configurable
  onPromptAction,
}: RealTimeCoachingProps) => {
  const { toast } = useToast();
  const [prompts, setPrompts] = useState<CoachingPrompt[]>([]);
  const [isActive, setIsActive] = useState(true);
  const [callDuration, setCallDuration] = useState(0);

  // Simulate real-time prompts (in production, this would come from AI analysis of transcript)
  useEffect(() => {
    if (!isActive) return;

    // Simulate call duration timer
    const durationTimer = setInterval(() => {
      setCallDuration(prev => prev + 1);
    }, 1000);

    // Simulate incoming coaching prompts based on call patterns
    const promptGenerator = setInterval(() => {
      generateContextualPrompt();
    }, promptIntervalSeconds * 1000); // Configurable interval

    return () => {
      clearInterval(durationTimer);
      clearInterval(promptGenerator);
    };
  }, [isActive, callDuration, promptIntervalSeconds]);

  const generateContextualPrompt = () => {
    // In production, these would be generated by AI based on:
    // - Real-time transcription
    // - Sentiment analysis
    // - Keyword detection
    // - Call flow analysis
    // - Historical performance data

    const samplePrompts: Omit<CoachingPrompt, 'id' | 'timestamp'>[] = [
      {
        type: 'suggestion',
        priority: 'medium',
        title: 'Build Rapport',
        message: 'The customer mentioned they\'re from Texas. Ask about the recent weather!',
        trigger: 'Geographic mention detected',
        actionable: true,
      },
      {
        type: 'objection',
        priority: 'high',
        title: 'Price Objection Detected',
        message: 'Customer said "too expensive". Try: "I understand budget is important. Let me show you how this pays for itself in 6 months..."',
        trigger: 'Price objection keywords',
        actionable: true,
      },
      {
        type: 'compliance',
        priority: 'high',
        title: 'Disclosure Required',
        message: 'Remind the customer this call may be recorded for quality assurance.',
        trigger: 'TCPA compliance check',
        actionable: true,
      },
      {
        type: 'next-action',
        priority: 'medium',
        title: 'Move to Close',
        message: 'Customer has shown interest 3 times. Suggest booking a demo or trial.',
        trigger: 'Buying signals detected',
        actionable: true,
      },
      {
        type: 'script',
        priority: 'low',
        title: 'Value Proposition',
        message: 'Consider mentioning our 90-day money-back guarantee to address concerns.',
        trigger: 'Uncertainty detected',
        actionable: false,
      },
      {
        type: 'warning',
        priority: 'high',
        title: 'Compliance Alert',
        message: 'Avoid making income guarantees. Rephrase as "potential earnings" or "typical results".',
        trigger: 'Risky language detected',
        actionable: true,
      },
      {
        type: 'suggestion',
        priority: 'medium',
        title: 'Active Listening',
        message: 'You\'ve been speaking for 90 seconds. Ask an open-ended question.',
        trigger: 'Talk ratio imbalance',
        actionable: true,
      },
      {
        type: 'objection',
        priority: 'high',
        title: 'Timing Objection',
        message: 'Customer said "not now". Try: "I understand timing is everything. When would be better - next quarter or after the new year?"',
        trigger: 'Timing objection keywords',
        actionable: true,
      },
    ];

    const randomPrompt = samplePrompts[Math.floor(Math.random() * samplePrompts.length)];
    
    const newPrompt: CoachingPrompt = {
      ...randomPrompt,
      id: `prompt-${Date.now()}`,
      timestamp: new Date(),
    };

    setPrompts(prev => [newPrompt, ...prev].slice(0, 10)); // Keep last 10 prompts

    // Show high-priority prompts as toast notifications
    if (newPrompt.priority === 'high') {
      toast({
        title: `🎯 ${newPrompt.title}`,
        description: newPrompt.message,
        duration: 8000,
      });
    }
  };

  const handlePromptAction = (promptId: string, action: string) => {
    // Mark prompt as acted upon
    setPrompts(prev =>
      prev.map(p =>
        p.id === promptId ? { ...p, actionable: false } : p
      )
    );

    // Call parent handler if provided
    onPromptAction?.(promptId, action);

    toast({
      title: "Prompt Acknowledged",
      description: "Great job following the coaching suggestion!",
    });
  };

  const dismissPrompt = (promptId: string) => {
    setPrompts(prev => prev.filter(p => p.id !== promptId));
  };

  const getPromptIcon = (type: CoachingPrompt['type']) => {
    switch (type) {
      case 'suggestion':
        return <Lightbulb className="h-4 w-4" />;
      case 'objection':
        return <MessageSquare className="h-4 w-4" />;
      case 'compliance':
        return <Shield className="h-4 w-4" />;
      case 'next-action':
        return <TrendingUp className="h-4 w-4" />;
      case 'script':
        return <CheckCircle2 className="h-4 w-4" />;
      case 'warning':
        return <AlertTriangle className="h-4 w-4" />;
    }
  };

  const getPriorityColor = (priority: CoachingPrompt['priority']) => {
    switch (priority) {
      case 'high':
        return 'destructive';
      case 'medium':
        return 'default';
      case 'low':
        return 'secondary';
    }
  };

  const formatDuration = (seconds: number) => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins}:${secs.toString().padStart(2, '0')}`;
  };

  return (
    <Card className="w-full">
      <CardHeader className="pb-3">
        <div className="flex items-center justify-between">
          <div>
            <CardTitle className="text-lg flex items-center gap-2">
              <Lightbulb className="h-5 w-5 text-yellow-500" />
              AI Coach
            </CardTitle>
            <CardDescription className="mt-1">
              Real-time suggestions during call
            </CardDescription>
          </div>
          <div className="text-right">
            <div className="text-2xl font-mono font-bold">
              {formatDuration(callDuration)}
            </div>
            <div className="text-xs text-muted-foreground">Call Duration</div>
          </div>
        </div>
      </CardHeader>
      <CardContent>
        <ScrollArea className="h-[400px] w-full pr-4">
          {prompts.length === 0 ? (
            <div className="flex flex-col items-center justify-center h-[300px] text-center">
              <Lightbulb className="h-12 w-12 text-muted-foreground/50 mb-4" />
              <p className="text-muted-foreground">
                AI coaching will appear here during the call
              </p>
              <p className="text-sm text-muted-foreground mt-2">
                Listening for opportunities to help...
              </p>
            </div>
          ) : (
            <div className="space-y-3">
              {prompts.map((prompt) => (
                <Card key={prompt.id} className="relative">
                  <CardContent className="p-4">
                    <div className="flex items-start gap-3">
                      <div className={`mt-1 ${
                        prompt.priority === 'high' ? 'text-red-500' :
                        prompt.priority === 'medium' ? 'text-blue-500' :
                        'text-gray-500'
                      }`}>
                        {getPromptIcon(prompt.type)}
                      </div>
                      
                      <div className="flex-1 space-y-2">
                        <div className="flex items-center gap-2">
                          <h4 className="font-semibold text-sm">
                            {prompt.title}
                          </h4>
                          <Badge variant={getPriorityColor(prompt.priority)} className="text-xs">
                            {prompt.priority}
                          </Badge>
                        </div>
                        
                        <p className="text-sm text-muted-foreground">
                          {prompt.message}
                        </p>
                        
                        <div className="flex items-center gap-2 text-xs text-muted-foreground">
                          <span>{prompt.trigger}</span>
                          <span>•</span>
                          <span>{new Date(prompt.timestamp).toLocaleTimeString()}</span>
                        </div>
                        
                        {prompt.actionable && (
                          <div className="flex gap-2 mt-3">
                            <Button
                              size="sm"
                              variant="default"
                              onClick={() => handlePromptAction(prompt.id, 'applied')}
                            >
                              Applied
                            </Button>
                            <Button
                              size="sm"
                              variant="outline"
                              onClick={() => dismissPrompt(prompt.id)}
                            >
                              Dismiss
                            </Button>
                          </div>
                        )}
                      </div>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          )}
        </ScrollArea>
        
        <div className="mt-4 p-3 bg-muted rounded-lg">
          <div className="flex items-center justify-between text-sm">
            <span className="text-muted-foreground">Coach Status:</span>
            <Badge variant={isActive ? "default" : "secondary"}>
              {isActive ? "Active" : "Paused"}
            </Badge>
          </div>
          <div className="flex items-center justify-between text-sm mt-2">
            <span className="text-muted-foreground">Prompts Today:</span>
            <span className="font-semibold">{prompts.length}</span>
          </div>
        </div>
      </CardContent>
    </Card>
  );
};

export default RealTimeCoaching;
