// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/account-summary.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/shared.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
function requireAuthenticatedUser(ctx) {
  const userId = ctx.getUserId();
  const token = ctx.getToken();
  if (!ctx.isAuthenticated() || !userId || !token) {
    return null;
  }
  return { userId, token };
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  const supabaseUrl = getRuntimeEnv("SUPABASE_URL");
  const publishableKey = getRuntimeEnv("SUPABASE_PUBLISHABLE_KEY") ?? getRuntimeEnv("SUPABASE_ANON_KEY");
  if (!token || !supabaseUrl || !publishableKey) {
    throw new Error("MCP Supabase environment is not configured.");
  }
  return createClient(supabaseUrl, publishableKey, {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function getRuntimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get(name) ?? runtime.process?.env?.[name];
}
function clampLimit(value, fallback, ceiling) {
  if (!value || Number.isNaN(value)) return fallback;
  return Math.min(Math.max(Math.trunc(value), 1), ceiling);
}
function textResult(text, structuredContent) {
  return {
    content: [{ type: "text", text }],
    structuredContent
  };
}
function authErrorResult() {
  return {
    content: [{ type: "text", text: "Not authenticated. Connect this MCP server through OAuth and try again." }],
    isError: true
  };
}
function toolErrorResult(message) {
  return {
    content: [{ type: "text", text: message }],
    isError: true
  };
}

// src/lib/mcp/tools/account-summary.ts
var account_summary_default = defineTool({
  name: "get_account_summary",
  title: "Get account summary",
  description: "Summarize this signed-in user's Dial Smart leads, campaigns, recent calls, and phone-number inventory.",
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async (_args, ctx) => {
    const auth2 = requireAuthenticatedUser(ctx);
    if (!auth2) return authErrorResult();
    try {
      const db = supabaseForUser(ctx);
      const since24h = new Date(Date.now() - 24 * 60 * 60 * 1e3).toISOString();
      const [leads, activeCampaigns, recentCalls, activeNumbers, dncLeads] = await Promise.all([
        db.from("leads").select("id", { count: "exact", head: true }),
        db.from("campaigns").select("id", { count: "exact", head: true }).eq("status", "active"),
        db.from("call_logs").select("id", { count: "exact", head: true }).gte("created_at", since24h),
        db.from("phone_numbers").select("id", { count: "exact", head: true }).eq("status", "active"),
        db.from("leads").select("id", { count: "exact", head: true }).eq("do_not_call", true)
      ]);
      const errors = [leads.error, activeCampaigns.error, recentCalls.error, activeNumbers.error, dncLeads.error].filter(Boolean);
      if (errors.length > 0) return toolErrorResult(errors[0]?.message ?? "Could not load account summary.");
      const summary = {
        userId: auth2.userId,
        totalLeads: leads.count ?? 0,
        activeCampaigns: activeCampaigns.count ?? 0,
        callsLast24h: recentCalls.count ?? 0,
        activePhoneNumbers: activeNumbers.count ?? 0,
        doNotCallLeads: dncLeads.count ?? 0
      };
      return textResult(
        `Account summary: ${summary.totalLeads} leads, ${summary.activeCampaigns} active campaigns, ${summary.callsLast24h} calls in the last 24 hours, ${summary.activePhoneNumbers} active phone numbers, and ${summary.doNotCallLeads} DNC leads.`,
        { summary }
      );
    } catch (error) {
      return toolErrorResult(error instanceof Error ? error.message : "Could not load account summary.");
    }
  }
});

// src/lib/mcp/tools/campaigns.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
var campaigns_default = defineTool2({
  name: "list_campaigns",
  title: "List campaigns",
  description: "List this signed-in user's Dial Smart campaigns with basic pacing and provider configuration.",
  inputSchema: {
    status: z.string().optional().describe("Optional campaign status filter such as active, paused, completed, or draft."),
    limit: z.number().int().optional().describe("Maximum campaigns to return. The tool clamps this to a safe limit.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ status, limit }, ctx) => {
    if (!requireAuthenticatedUser(ctx)) return authErrorResult();
    try {
      const db = supabaseForUser(ctx);
      const safeLimit = clampLimit(limit, 20, 50);
      let query = db.from("campaigns").select("id,name,status,provider,agent_id,telnyx_assistant_id,calls_per_minute,max_attempts,retry_delay_minutes,calling_hours_start,calling_hours_end,timezone,created_at,updated_at").order("updated_at", { ascending: false }).limit(safeLimit);
      if (status?.trim()) query = query.eq("status", status.trim());
      const { data, error } = await query;
      if (error) return toolErrorResult(error.message);
      const items = data ?? [];
      return textResult(
        items.length ? `Found ${items.length} campaign${items.length === 1 ? "" : "s"}.` : "No matching campaigns found.",
        { items }
      );
    } catch (error) {
      return toolErrorResult(error instanceof Error ? error.message : "Could not list campaigns.");
    }
  }
});

// src/lib/mcp/tools/leads.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
function sanitizeSearchTerm(value) {
  return value.replace(/[,%()]/g, " ").trim();
}
var leads_default = defineTool3({
  name: "search_leads",
  title: "Search leads",
  description: "Search this signed-in user's leads by status, name, company, email, or phone number.",
  inputSchema: {
    query: z2.string().optional().describe("Optional text or phone search term."),
    status: z2.string().optional().describe("Optional exact lead status filter."),
    dueCallbacksOnly: z2.boolean().optional().describe("When true, return only leads with callbacks due now or earlier."),
    limit: z2.number().int().optional().describe("Maximum leads to return. The tool clamps this to a safe limit.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ query, status, dueCallbacksOnly, limit }, ctx) => {
    if (!requireAuthenticatedUser(ctx)) return authErrorResult();
    try {
      const db = supabaseForUser(ctx);
      const safeLimit = clampLimit(limit, 25, 50);
      let request = db.from("leads").select("id,first_name,last_name,company,email,phone_number,status,priority,lead_source,tags,do_not_call,next_callback_at,last_contacted_at,created_at,updated_at").order("updated_at", { ascending: false }).limit(safeLimit);
      if (status?.trim()) request = request.eq("status", status.trim());
      if (dueCallbacksOnly) request = request.lte("next_callback_at", (/* @__PURE__ */ new Date()).toISOString()).not("next_callback_at", "is", null);
      const term = query ? sanitizeSearchTerm(query) : "";
      if (term) {
        const pattern = `%${term}%`;
        request = request.or(`first_name.ilike.${pattern},last_name.ilike.${pattern},company.ilike.${pattern},email.ilike.${pattern},phone_number.ilike.${pattern}`);
      }
      const { data, error } = await request;
      if (error) return toolErrorResult(error.message);
      const items = data ?? [];
      return textResult(
        items.length ? `Found ${items.length} lead${items.length === 1 ? "" : "s"}.` : "No matching leads found.",
        { items }
      );
    } catch (error) {
      return toolErrorResult(error instanceof Error ? error.message : "Could not search leads.");
    }
  }
});

// src/lib/mcp/tools/phone-number-health.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var phone_number_health_default = defineTool4({
  name: "list_phone_number_health",
  title: "List phone-number health",
  description: "List this signed-in user's phone numbers with lightweight health flags for campaign readiness.",
  inputSchema: {
    provider: z3.string().optional().describe("Optional provider filter such as retell, telnyx, or twilio."),
    limit: z3.number().int().optional().describe("Maximum phone numbers to return. The tool clamps this to a safe limit.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ provider, limit }, ctx) => {
    if (!requireAuthenticatedUser(ctx)) return authErrorResult();
    try {
      const db = supabaseForUser(ctx);
      const safeLimit = clampLimit(limit, 50, 100);
      let request = db.from("phone_numbers").select("id,number,provider,status,purpose,daily_calls,max_daily_calls,is_spam,rotation_enabled,quarantine_until,last_call_at,retell_phone_id,twilio_sid,updated_at").order("updated_at", { ascending: false }).limit(safeLimit);
      if (provider?.trim()) request = request.eq("provider", provider.trim());
      const { data, error } = await request;
      if (error) return toolErrorResult(error.message);
      const now = Date.now();
      const items = (data ?? []).map((number) => {
        const maxDailyCalls = number.max_daily_calls ?? 100;
        const atDailyCap = number.daily_calls >= maxDailyCalls;
        const quarantined = Boolean(number.quarantine_until && new Date(number.quarantine_until).getTime() > now);
        const flags = [
          number.status !== "active" ? "inactive" : null,
          number.is_spam ? "spam_flagged" : null,
          quarantined ? "quarantined" : null,
          atDailyCap ? "at_daily_cap" : null,
          number.rotation_enabled === false ? "rotation_disabled" : null
        ].filter(Boolean);
        return {
          ...number,
          max_daily_calls: maxDailyCalls,
          health: flags.length === 0 ? "healthy" : flags.length === 1 ? "watch" : "unhealthy",
          flags
        };
      });
      return textResult(
        items.length ? `Found ${items.length} phone number${items.length === 1 ? "" : "s"}.` : "No matching phone numbers found.",
        { items }
      );
    } catch (error) {
      return toolErrorResult(error instanceof Error ? error.message : "Could not list phone-number health.");
    }
  }
});

// src/lib/mcp/tools/recent-calls.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
var recent_calls_default = defineTool5({
  name: "list_recent_calls",
  title: "List recent calls",
  description: "List this signed-in user's recent call records with outcomes, providers, durations, and summaries.",
  inputSchema: {
    campaignId: z4.string().optional().describe("Optional campaign id filter."),
    status: z4.string().optional().describe("Optional exact call status filter."),
    limit: z4.number().int().optional().describe("Maximum calls to return. The tool clamps this to a safe limit.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ campaignId, status, limit }, ctx) => {
    if (!requireAuthenticatedUser(ctx)) return authErrorResult();
    try {
      const db = supabaseForUser(ctx);
      const safeLimit = clampLimit(limit, 20, 50);
      let request = db.from("call_logs").select("id,campaign_id,lead_id,phone_number,caller_id,status,outcome,auto_disposition,provider,duration_seconds,sentiment,call_summary,created_at,started_at,ended_at").order("created_at", { ascending: false }).limit(safeLimit);
      if (campaignId?.trim()) request = request.eq("campaign_id", campaignId.trim());
      if (status?.trim()) request = request.eq("status", status.trim());
      const { data, error } = await request;
      if (error) return toolErrorResult(error.message);
      const items = data ?? [];
      return textResult(
        items.length ? `Found ${items.length} recent call${items.length === 1 ? "" : "s"}.` : "No matching calls found.",
        { items }
      );
    } catch (error) {
      return toolErrorResult(error instanceof Error ? error.message : "Could not list recent calls.");
    }
  }
});

// src/lib/mcp/index.ts
var projectRef = "emonjusymdripmkvtttc";
var mcp_default = defineMcp({
  name: "dial-smart-mcp",
  title: "Dial Smart Agent Integrations",
  version: "0.1.0",
  instructions: "Read-only Dial Smart tools for the signed-in user. Use these tools to inspect campaign readiness, leads, recent calls, and phone-number health. Never infer access to data outside the OAuth-connected user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [account_summary_default, campaigns_default, leads_default, recent_calls_default, phone_number_health_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
